(function(g){var window=this;var KDa=function(a,b){return g.dc(a,b)},a6=function(a){g.ln(a,"zx",g.Db());
return a},b6=function(a,b,c){g.Da(c)||(c=[String(c)]);
g.on(a.o,b,c)},LDa=function(a,b){var c=[];
g.Wk(b,function(a){try{var b=g.MD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.LD(b)&&c.push(a):c.push(a)},a);
return c},MDa=function(a,b){var c=LDa(a,b);
(0,g.E)(c,function(a){g.MD.prototype.remove.call(this,a)},a)},NDa=function(a){if(a.Rd){if(a.Rd.locationOverrideToken)return{locationOverrideToken:a.Rd.locationOverrideToken};
if(null!=a.Rd.latitudeE7&&null!=a.Rd.longitudeE7)return{latitudeE7:a.Rd.latitudeE7,longitudeE7:a.Rd.longitudeE7}}return null},ODa=function(a,b,c,d){var e=new g.bn(null,void 0);
a&&g.cn(e,a);b&&g.dn(e,b);c&&g.en(e,c);d&&g.fn(e,d);return e},PDa=function(a){return a?a.dataset?a.dataset[g.CF("loaded")]:a.getAttribute("data-loaded"):null},c6=function(a,b){g.vG[a]=!0;
var c=g.tG();c&&c.publish.apply(c,arguments);g.vG[a]=!1},QDa=function(a){g.wG[a]&&(a=g.wG[a],(0,g.E)(a,function(a){g.uG[a]&&delete g.uG[a]}),a.length=0)},RDa=function(a){var b=g.tG();
if(b)if(b.clear(a),a)QDa(a);else for(var c in g.wG)QDa(c)},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Wm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",SDa(this,a.capabilities||""),TDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},SDa=function(a,b){a.capabilities.clear();
(0,g.fe)(b.split(","),g.Ja(KDa,UDa)).forEach(function(b){a.capabilities.add(b)})},TDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},VDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},WDa=function(a){return new e6(a)},XDa=function(a){return g.Da(a)?(0,g.J)(a,WDa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Da(a)?"["+(0,g.J)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},YDa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},j6=function(a,b){return g.Qa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},k6=function(a,b){return g.Qa(a,function(a){return f6(a,b)})},ZDa=function(){var a=(0,g.EH)();
a&&MDa(a,a.o.ie(!0))},l6=function(){var a=g.HH("yt-remote-connected-devices")||[];
g.pb(a);return a},$Da=function(a){if(g.Wa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},aEa=function(a){g.GH("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.HH("yt-remote-device-id");a||(a=i6(),g.GH("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.Va(a,b);g.JH()&&g.rb(a,b);a=$Da(a);if(g.Wa(a))try{g.cH("remote_sid")}catch(c){}else try{g.bH("remote_sid",a.join(","),-1)}catch(c){}},bEa=function(){return g.HH("yt-remote-session-browser-channel")},cEa=function(){return g.HH("yt-remote-local-screens")||[]},dEa=function(){g.GH("yt-remote-lounge-token-expiration",!0,86400)},eEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(cEa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Km)(c,function(a){return!g.Va(b,a)})&&dEa();
g.GH("yt-remote-local-screens",a,31536E3)},fEa=function(a,b){g.GH("yt-remote-session-browser-channel",a);
g.GH("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.Va(c,d)||c.push(d);aEa(c);o6()},p6=function(a){a||(g.IH("yt-remote-session-screen-id"),g.IH("yt-remote-session-video-id"));
o6();a=l6();g.$a(a,n6());aEa(a)},gEa=function(){if(!q6){var a=g.XD();
a&&(q6=new g.GD(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},hEa=function(){var a=window.document.createElement("a");
g.td(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Hb(a)},iEa=function(a,b,c){c=void 0===c?null:c;
var d=g.Zd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.wd(d,g.ve("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},jEa=function(a){a=void 0===a?null:a;
var b=hEa(),c=window.document.getElementById(b),d=c&&PDa(c);d||c&&!d||(c=iEa(b,function(){PDa(c)||(g.DF(c,"loaded","true"),g.AG(b),g.CE(g.Ja(RDa,b),0))},a))},kEa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):jEa(a)},r6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},lEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?mEa(a.shift(),function(){s6(a)}):t6()},nEa=function(a){return"chrome-extension://"+a+u6},mEa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},v6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},t6=function(){var a=lEa();
a&&a(!1,"No cast extension found")},w6=function(){if(oEa){var a=2,b=lEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;mEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},pEa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(w6(),a({command:"cast.sender.init"}))},qEa=function(){w6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+u6,"//www.gstatic.com/eureka/clank"+u6])},x6=function(a,b,c){g.K.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Id=b;this.D=(0,g.B)(this.SK,this);this.o=!1;this.A=0;this.B=this.Ha=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.sn(this);this.A=new g.Ig;this.A.setInterval(250)},sEa=function(a,b,c){a.Yj=1;
a.Ah=a6(b.clone());a.oj=c;a.D=!0;rEa(a,null)},A6=function(a,b,c,d,e){a.Yj=1;
a.Ah=a6(b.clone());a.oj=null;a.D=c;e&&(a.wF=!1);rEa(a,d)},rEa=function(a,b){a.Vk=(0,g.I)();
B6(a);a.di=a.Ah.clone();b6(a.di,"t",a.F);a.Pn=0;a.Yc=a.o.Us(a.o.Hn()?b:null);0<a.Pt&&(a.Nq=new g.Dl((0,g.B)(a.KG,a,a.Yc),a.Pt));a.Y.W(a.Yc,"readystatechange",a.dW);var c=a.Oi?g.mc(a.Oi):{};a.oj?(a.Dr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Yc.send(a.di,a.Dr,a.oj,c)):(a.Dr="GET",a.wF&&!g.Ud&&(c.Connection="close"),a.Yc.send(a.di,a.Dr,null,c));a.o.Hf(1)},vEa=function(a,b,c){for(var d=!0;!a.zi&&a.Pn<c.length;){var e=tEa(a,c);
if(e==C6){4==b&&(a.Bh=4,D6(15),d=!1);break}else if(e==uEa){a.Bh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Bh=1,D6(17),d=!1);a.Of=a.Of&&d;d||(F6(a),G6(a))},tEa=function(a,b){var c=a.Pn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return uEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Pn=d+c;return e},xEa=function(a,b){a.Vk=(0,g.I)();
B6(a);var c=b?window.location.hostname:"";a.di=a.Ah.clone();g.ln(a.di,"DOMAIN",c);g.ln(a.di,"t",a.F);try{a.Pf=new window.ActiveXObject("htmlfile")}catch(n){F6(a);a.Bh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in wEa)k=H6[l]=wEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.xd(g.Lc("b/12014412"),d+"</body></html>");a.Pf.open();a.Pf.write(g.md(c));a.Pf.close();a.Pf.parentWindow.m=(0,g.B)(a.mV,a);a.Pf.parentWindow.d=(0,g.B)(a.EE,a,!0);a.Pf.parentWindow.rpcClose=(0,g.B)(a.EE,a,!1);c=a.Pf.createElement("DIV");a.Pf.parentWindow.document.body.appendChild(c);d=g.Zc(a.di.toString());d=g.xb(g.Wc(d));d=g.xd(g.Lc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.sd(c,g.md(d));a.o.Hf(1)},
B6=function(a){a.Lx=(0,g.I)()+a.C;
yEa(a,a.C)},yEa=function(a,b){if(null!=a.sl)throw Error("WatchDog timer not null");
a.sl=I6((0,g.B)(a.BV,a),b)},J6=function(a){a.sl&&(g.x.clearTimeout(a.sl),a.sl=null)},G6=function(a){a.o.XA()||a.zi||a.o.Aq(a)},F6=function(a){J6(a);
g.uf(a.Nq);a.Nq=null;a.A.stop();g.yn(a.Y);if(a.Yc){var b=a.Yc;a.Yc=null;b.abort();b.dispose()}a.Pf&&(a.Pf=null)},E6=function(a,b){try{a.o.wE(a,b),a.o.Hf(4)}catch(c){}},AEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;zEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){AEa(a,b,c,d,f)},f)})}},zEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},BEa=function(a){this.o=a;
this.A=new y6},CEa=function(a){var b=L6(a.o,a.yl,"/mail/images/cleardot.gif");
a6(b);AEa(b.toString(),5E3,(0,g.B)(a.WJ,a),3,2E3);a.Hf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Ke=new z6(a,void 0,void 0,void 0),a.Ke.Oi=a.Nt,b=a.o,b=L6(b,b.Hn()?a.pm:null,a.Ot),D6(5),!g.Sd||g.Dc(10))b6(b,"TYPE","xmlhttp"),A6(a.Ke,b,!1,a.pm,!1);else{b6(b,"TYPE","html");var c=a.Ke;a=!!a.pm;c.Yj=3;c.Ah=a6(b.clone());xEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},DEa=function(a,b){this.o=a;
this.map=b;this.context=null},EEa=function(a){g.wf.call(this,"statevent",a)},FEa=function(a,b){g.wf.call(this,"timingevent",a);
this.size=b},GEa=function(a){g.wf.call(this,"serverreachability",a)},JEa=function(a){HEa(a);
if(3==a.o){var b=a.mn++,c=a.hp.clone();g.ln(c,"SID",a.B);g.ln(c,"RID",b);g.ln(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.Yj=2;b.Ah=a6(c.clone());(new window.Image).src=b.Ah;b.Vk=(0,g.I)();B6(b)}IEa(a)},KEa=function(a){a.sK(1,0);
a.hp=L6(a,null,a.Mt);Q6(a)},HEa=function(a){a.oh&&(a.oh.abort(),a.oh=null);
a.Cc&&(a.Cc.cancel(),a.Cc=null);a.Cg&&(g.x.clearTimeout(a.Cg),a.Cg=null);R6(a);a.pe&&(a.pe.cancel(),a.pe=null);a.uh&&(g.x.clearTimeout(a.uh),a.uh=null)},LEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new DEa(a.dR++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.pe||a.uh||(a.uh=I6((0,g.B)(a.CE,a),0),a.Oj=0)},NEa=function(a,b){if(1==a.o){if(!b){a.mn=Math.floor(1E5*Math.random());
var c=a.mn++,d=new z6(a,"",c,void 0);d.Oi=null;var e=S6(a),f=a.hp.clone();g.ln(f,"RID",c);g.ln(f,"CVER","1");P6(a,f);sEa(d,f,e);a.pe=d;a.o=2}}else 3==a.o&&(b?MEa(a,b):0==a.A.length||a.pe||MEa(a))},MEa=function(a,b){if(b)if(6<a.Bi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.mn-1;var d=S6(a)}else c=b.G,d=b.oj;else c=a.mn++,d=S6(a);var e=a.hp.clone();g.ln(e,"SID",a.B);g.ln(e,"RID",c);g.ln(e,"AID",a.tk);P6(a,e);c=new z6(a,a.B,c,a.Oj+1);c.Oi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.pe=c;sEa(c,e,d)},P6=function(a,b){if(a.Hd){var c=a.Hd.FA();
c&&g.Qb(c,function(a,c){g.ln(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Bi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Bi?e:f-d;try{g.Qb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},OEa=function(a){a.Cc||a.Cg||(a.G=1,a.Cg=I6((0,g.B)(a.BE,a),0),a.Fj=0)},T6=function(a){if(a.Cc||a.Cg||3<=a.Fj)return!1;
a.G++;a.Cg=I6((0,g.B)(a.BE,a),PEa(a,a.Fj));a.Fj++;return!0},M6=function(a,b,c){a.Br=c;
a.Zf=b.Og;a.F||KEa(a)},R6=function(a){null!=a.Di&&(g.x.clearTimeout(a.Di),a.Di=null)},PEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Hd&&(c=null);var d=(0,g.B)(a.TW,a);c||(c=new g.bn("//www.google.com/images/cleardot.gif"),a6(c));zEa(c.toString(),1E4,d)}else D6(2);QEa(a,b)},QEa=function(a,b){a.o=0;
a.Hd&&a.Hd.Fz(b);IEa(a);HEa(a)},IEa=function(a){a.o=0;
a.Zf=-1;if(a.Hd)if(0==a.C.length&&0==a.A.length)a.Hd.Hs();else{g.db(a.C);var b=g.db(a.A);a.C.length=0;a.A.length=0;a.Hd.Hs(b)}},L6=function(a,b,c){var d=g.mn(c);
if(""!=d.A)b&&g.dn(d,b+"."+d.A),g.en(d,d.D);else{var e=window.location;d=ODa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ol&&g.Qb(a.Ol,function(a,b){g.ln(d,b,a)});
g.ln(d,"VER",a.Bi);P6(a,d);return d},I6=function(a,b){if(!g.Fa(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new EEa(V6,a))},REa=function(){},SEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.K.call(this);
this.o=new g.V(this.dV,0,this);g.M(this,this.o);this.Id=5E3;this.A=0;if(g.Fa(a))b&&(a=(0,g.B)(a,b));else if(a&&g.Fa(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.L=a;
this.F=b;this.B=new g.FD;this.A=new W6(this.wX,this);this.o=this.kb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},TEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Br,sessionId:a.o.B,arrayId:a.o.tk}},UEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&NEa(a.o),JEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},VEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Ob;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.fh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ja(a.C,d,!0),onError:g.Ja(a.B,e),Nd:g.Ja(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.TE(b,a)},ZEa=function(){var a=WEa;
XEa();b7.push(a);YEa(b7)},c7=function(a,b){XEa();
var c=b7,d=$Ea(a,String(b));g.Wa(c)?aFa(d):(YEa(c),(0,g.E)(c,function(a){a(d)}))},XEa=function(){b7||(b7=g.y("yt.mdx.remote.debug.handlers_")||[],g.Aa("yt.mdx.remote.debug.handlers_",b7,void 0))},aFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},YEa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.E)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},$Ea=function(a,b){var c=((0,g.I)()-bFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.kG.call(this);
this.G=a;this.o=[]},cFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},dFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.fe)(a.o,function(a){return!!j6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=cFa(a,b[d])||c;return c},eFa=function(a,b){var c=a.o.length;
a.o=(0,g.fe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.kG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ha=window.NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;i7(this);this.info("Initializing with "+h6(this.o))},fFa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.gL,a),(0,g.B)(a.fL,a))}},i7=function(a){var b=XDa(cEa());
b=(0,g.fe)(b,function(a){return!a.uuid});
return dFa(a,b)},k7=function(a,b){eEa((0,g.J)(a.o,VDa));
b&&dEa()},m7=function(a,b){g.kG.call(this);
this.F=b;var c=g.HH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;l7("Initialized with "+g.Og(this.o))},gFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Vb(b)!=g.Vb(a.o))var c=!1;
else{c=g.ac(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Og(a.o)),a.o=b,a.U("screenChange"));hFa(a)},o7=function(a){(0,window.isNaN)(a.B)||g.EE(a.B);
a.B=g.CE((0,g.B)(a.Iw,a),0<a.C&&a.C<(0,g.I)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},iFa=function(a){var b={};
(0,g.E)(a.F(),function(a){a.token?b[a.token]=a.id:this.xc("Requesting availability of screen w/o lounge token.")});
return b},hFa=function(a){a=g.ac(g.Rb(a.o,function(a){return a}));
g.pb(a);a.length?g.GH("yt-remote-online-screen-ids",a.join(","),60):g.IH("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};jFa(this)},lFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Fe();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=q7(a,k);gFa(a.A,l,function(a){e(a?l:null)})}else c?kFa(a,c,(0,g.B)(function(a){var f=q7(this,new e6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));gFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},mFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},kFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.TE($6(a.F,"/pairing/get_lounge_token_batch"),e)},nFa=function(a){a.o=a.B.Fe();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},jFa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.tL,a));nFa(a);a.C=XDa(g.HH("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+h6(a.C));a.A=new m7(a.F,(0,g.B)(a.Fe,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.GH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,VDa)));r7(a);a.D[b.uuid]=b.id;g.GH("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.HH("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.kG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.CX,this);this.D=(0,g.B)(this.OV,this);this.C=g.CE((0,g.B)(function(){oFa(this,null)},this),12E4)},pFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Og(b))},oFa=function(a,b){g.EE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Bq,a),d=(0,g.B)(a.Je,a);a.NA(b,c,d,5)}}else a.Je(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.FX,this);this.o=g.A},qFa=function(a){a.o=a.J.TG(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Bq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Je(a)},a))},rFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}gEa()&&(b.env_useStageMdx=1);return g.dh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.CE((0,g.B)(this.vk,this,null),150)},x7=function(a,b,c,d){g.kG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.rU,this)},sFa=function(a,b){return b?g.Qa(a.B,function(a){return f6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},WEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.uf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.zE,a,b)),b.B?a.U("yt-remote-cast2-session-change",b.B):c&&a.o.vk(null)):a.U("yt-remote-cast2-session-change",null))},tFa=function(a){var b=a.A.SG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&f6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=sFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},zFa=function(a,b,c,d,e,f,k){uFa()?vFa(b,e,f,k)&&(C7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?wFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?wFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.IH("yt-remote-cast-available"),g.IH("yt-remote-cast-receiver"),xFa(),
c(!1))},d?kEa():v6("CriOS")?pEa():v6("Android")&&v6("Chrome/")&&window.navigator.presentation?qEa():window.chrome&&window.navigator.presentation&&!v6("Edge")?(w6(),s6(yFa.map(nEa))):t6())):B7("Cannot initialize because not running Chrome")},xFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Aa("yt.mdx.remote.cloudview.instance_",null,void 0);AFa(!1);g.yG(G7);G7.length=0},H7=function(){return!!g.HH("yt-remote-cast-installed")},BFa=function(){var a=g.HH("yt-remote-cast-receiver");
return a?a.friendlyName:null},CFa=function(){B7("clearCurrentReceiver");
g.IH("yt-remote-cast-receiver")},DFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.xG("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},uFa=function(){var a=0<=g.Ob.search(/ (CrMo|Chrome|CriOS)\//);
return g.SI||a},EFa=function(a,b){F7().init(a,b)},vFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.GH("yt-remote-cast-available",a);c6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.GH("yt-remote-cast-receiver",a);c6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.GH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+g6(a));
a||g.IH("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",a)}),g.Aa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},wFa=function(a,b){E7(!0);
C7(!1);EFa(a,function(a){a?(AFa(!0),g.AG("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.IH("yt-remote-cast-available"),g.IH("yt-remote-cast-receiver"),xFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.GH("yt-remote-cast-installed",a)},I7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},AFa=function(a){B7("setApiReady_ "+a);
g.Aa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Aa("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.eg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.eg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.I)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.I)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.I)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.nc(a.o);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.kG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.WC;this.B=this.A=null;this.J=(0,g.B)(this.NR,this);this.G=(0,g.B)(this.qn,this);this.H=(0,g.B)(this.MR,this);this.K=(0,g.B)(this.ZR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Tx,this),FFa(this))):c=3;0!=c&&(b?this.Tx(c):g.CE((0,g.B)(function(){this.Tx(c)},this),0));
var d=DFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},FFa=function(a){(0,g.E)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ja(this.mU,a),this))},a)},GFa=function(a){(0,g.E)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Nc()&&g.YC(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){GFa(a);
a.C.setPlayerContextData(R7(b));FFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.qn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.qn(a.B.media[0]))},HFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.B)(function(a){this.xc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.xc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.kG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.V=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.V.push(g.UF(window,"beforeunload",(0,g.B)(this.WK,this)));this.A=[];this.qb=new L7;this.ba=b.id;this.o=IFa(this,c);this.o.subscribe("handlerOpened",this.RR,this);this.o.subscribe("handlerClosed",this.OR,this);this.o.subscribe("handlerError",this.PR,this);this.o.subscribe("handlerMessage",this.QR,this);VEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.qb.videoId;g.JH()&&g.GH("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},IFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},JFa=function(a){a.D=g.CE((0,g.B)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.EE(a.D);
a.D=window.NaN},d8=function(a){g.EE(a.M);
a.M=window.NaN},KFa=function(a){e8(a);
a.L=g.CE((0,g.B)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.EE(a.L);
a.L=window.NaN},MFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&(0,window.isNaN)(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),LFa(a)):a.F(1)},NFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.hc(b.params)?a.qb.o=null:a.qb.o=b.params,a.U("remotePlayerChange"))},OFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.U("remoteQueueChange")},QFa=function(a,b){b.params=b.params||{};
OFa(a,b);PFa(a,b);a.U("autoplayDismissed")},PFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
O7(a.qb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.qb.H=(0,window.isNaN)(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.qb.playerState?KFa(a):e8(a);a.U("remotePlayerChange")},RFa=function(a,b){if(-1E3!=a.qb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);O7(a.qb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},SFa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=(0,window.parseInt)(b.params.volume,10);a.qb.muted=c;a.U("remotePlayerChange")},TFa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},UFa=function(a,b){var c="true"==b.params.hasNext;
a.qb.eg="true"==b.params.hasPrevious;a.qb.hasNext=c;a.U("previousNextChange")},LFa=function(a){g.EE(a.K);
a.K=g.CE((0,g.B)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Og(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.qd=a;this.A=[];this.A.push(this.qd.$_s("screenChange",(0,g.B)(this.AX,this)));this.A.push(this.qd.$_s("onlineScreenChange",(0,g.B)(this.IT,this)))},ZFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.rE("MDX_CONFIG")||b;ZDa();o6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),gEa()&&(h8.o="/api/loungedev"));i8||(i8=g.y("yt.mdx.remote.deferredProxies_")||[],g.Aa("yt.mdx.remote.deferredProxies_",i8,void 0));VFa();var c=j8();if(!c){var d=new p7(h8);g.Aa("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);zFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.Aa("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Og(b)),m8.push(g.xG("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),m8.push(g.xG("yt-remote-cast2-receiver-selected",function(){n8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.xG("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.xG("yt-remote-cast2-session-change",WFa)),m8.push(g.xG("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),CFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.zE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Og(a)),XFa(a),c.start(),k8()||YFa())},aGa=function(){var a=$Fa();
H7()&&g.HH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},$Fa=function(){var a=j8().qd.$_gos();
var b=q8();b&&r8()&&(j6(a,b)||a.push(b));return YDa(a)},s8=function(){var a=bGa();
!a&&H7()&&BFa()&&(a={key:"cast-selector-receiver",name:BFa()});return a},bGa=function(){var a=$Fa(),b=q8();
b||(b=o8());return g.Qa(a,function(a){return b&&f6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().Fe();return k6(b,a)},WFa=function(a){l8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.y("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.y("yt.mdx.remote.currentScreenId_")},cGa=function(a){g.Aa("yt.mdx.remote.currentScreenId_",a,void 0)},dGa=function(){return g.y("yt.mdx.remote.connectData_")},n8=function(a){g.Aa("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.y("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||cGa("");g.Aa("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.E)(i8,function(b){b(a)}),i8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},o8=function(){var a=g.JH();
if(!a)return null;var b=j8().Fe();return k6(b,a)},u8=function(a,b){q8()&&q8();
cGa(a.id);var c=new $7(h8,a,p8());c.connect(b,dGa());c.subscribe("beforeDisconnect",function(a){c6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},YFa=function(){var a=o8();
a?(l8("Resume connection to: "+g6(a)),u8(a,0)):(p6(),CFa(),l8("Skipping connecting because no session screen found."))},VFa=function(){var a=p8();
if(g.hc(a)){a=n6();var b=g.HH("yt-remote-session-name")||"",c=g.HH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Aa("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},XFa=function(a){a?(g.GH("yt-remote-session-app",a.app),g.GH("yt-remote-session-name",a.name)):(g.IH("yt-remote-session-app"),g.IH("yt-remote-session-name"));
g.Aa("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.K.call(this);
this.D=a;this.A=b;this.B=new g.hG(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.dT);this.B.R(b,"captionschanged",this.LR);this.B.R(b,"captionssettingschanged",this.bG);this.B.R(b,"videoplayerreset",this.Cq);this.B.R(b,"mdxautoplaycancel",this.VJ);this.V=this.B.R(b,"onVolumeChange",this.fE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.vE,this);c.subscribe("remotePlayerChange",this.vn,this);c.subscribe("remoteQueueChange",this.Cq,this);c.subscribe("autoplayUpNext",this.RD,
this);c.subscribe("previousNextChange",this.sE,this);c.subscribe("nowAutoplaying",this.kE,this);c.subscribe("autoplayDismissed",this.QD,this);this.suggestion=null;this.J=new g.bQ(64);this.C=new g.V(this.YF,500,this);g.M(this,this.C);this.F=new g.V(this.ZF,1E3,this);g.M(this,this.F);this.L=new x6(this.dX,0,this);g.M(this,this.L);this.G={};this.M=new g.V(this.zG,1E3,this);g.M(this,this.M);this.K=new g.Dl(this.MP,1E3,this);g.M(this,this.K);this.O=g.A;this.bG();this.Cq();this.vn()},z8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.U("progresssync",b,d)},eGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.bQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.Ug()},g.pc(c,b));a.o.OF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.pg();
if(c){var d=c.Ee();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.jk;f=NDa(f);var n=U7(c);l=l||0;var p={videoId:k,currentIndex:l};Q7(n,k,l);g.u(b)&&(O7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Og(f));Y7(c,"setPlaylist",p);e||W7(c,n);A8(a,new g.bQ(1))},fGa=function(a,b){if(b){var c=a.A.kc("captions","tracklist",{y5:1});
c&&c.length?(a.A.ed("captions","track",b),a.H=!1):(a.A.Ck("captions"),a.H=!0)}else a.A.ed("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.hQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.vU(a.A,d);a.J=b;gGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.lsa()]},{I:"div",N:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.rV(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);hGa(this,g.rU(a))},hGa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.kc("remote","currentReceiver").name};
c=g.X(b,128)?g.jV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.jV("Playing on $RECEIVER_NAME",c):g.jV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.UY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.UU.call(this,a);
this.A={key:i6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.bQ(64);this.J=0;this.G=-1;if(!g.BN(g.Z(this.player))){a=this.player;var b=g.tI(a);b&&(b=b.fn())&&(b=new F8(a,b),g.M(this,b));b=new E8(a);g.M(this,b);g.KU(a,b.element,4)}},gGa=function(a,b,c){a.F=c;
a.player.U("presentingplayerstatechange",new g.mQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.pg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ia(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.jk,index:Math.max(a.player.BC(),0),currentTime:0==f?void 0:f};(d=NDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?(n8(d||null),I7()?F7().setLaunchParams(d||
null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?c6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().Fe(),(d=k6(d,b.key))&&u8(d,1))}},wEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},iGa={},UDa={YY:"atp",D3:"ska",U2:"que",e2:"mus",z3:"sus",l0:"dsp"};
d6.prototype.ph=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var q6,m6="",u6=r6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",oEa=r6("loadCastFramework")||r6("loadCastApplicationFramework"),yFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(x6,g.K);g.h=x6.prototype;g.h.RK=function(a){this.C=arguments;this.o=!1;this.Ha?this.B=(0,g.I)()+this.Id:this.Ha=g.Jg(this.D,this.Id)};
g.h.stop=function(){this.Ha&&(g.Kg(this.Ha),this.Ha=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();x6.ga.X.call(this)};
g.h.SK=function(){this.B?(this.Ha=g.Jg(this.D,this.B-(0,g.I)()),this.B=null):(this.Ha=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Oi=null;g.h.Of=!1;g.h.sl=null;g.h.Lx=null;g.h.Vk=null;g.h.Yj=null;g.h.Ah=null;g.h.di=null;g.h.oj=null;g.h.Yc=null;g.h.Pn=0;g.h.Pf=null;g.h.Dr=null;g.h.Bh=null;g.h.qm=-1;g.h.wF=!0;g.h.zi=!1;g.h.Pt=0;g.h.Nq=null;var uEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.dW=function(a){a=a.target;var b=this.Nq;b&&3==g.Rx(a)?b.jm():this.KG(a)};
g.h.KG=function(a){try{if(a==this.Yc)a:{var b=g.Rx(this.Yc),c=this.Yc.A,d=this.Yc.getStatus();if(g.Sd&&!g.Dc(10)||g.Ud&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yf&&!g.Vx(this.Yc))break a;this.zi||4!=b||7==c||(8==c||0>=d?this.o.Hf(3):this.o.Hf(2));J6(this);var e=this.Yc.getStatus();this.qm=e;var f=g.Vx(this.Yc);(this.Of=200==e)?(4==b&&F6(this),this.D?(vEa(this,b,f),g.yf&&this.Of&&3==b&&(this.Y.W(this.A,"tick",this.aW),this.A.start())):E6(this,f),this.Of&&!this.zi&&(4==b?this.o.Aq(this):
(this.Of=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bh=3,D6(13)):(this.Bh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Yc&&g.Vx(this.Yc)}finally{}};
g.h.aW=function(){var a=g.Rx(this.Yc),b=g.Vx(this.Yc);this.Pn<b.length&&(J6(this),vEa(this,a,b),this.Of&&4!=a&&B6(this))};
g.h.mV=function(a){I6((0,g.B)(this.lV,this,a),0)};
g.h.lV=function(a){this.zi||(J6(this),E6(this,a),B6(this))};
g.h.EE=function(a){I6((0,g.B)(this.kV,this,a),0)};
g.h.kV=function(a){this.zi||(F6(this),this.Of=a,this.o.Aq(this),this.o.Hf(4))};
g.h.cancel=function(){this.zi=!0;F6(this)};
g.h.BV=function(){this.sl=null;var a=(0,g.I)();0<=a-this.Lx?(2!=this.Yj&&this.o.Hf(3),F6(this),this.Bh=2,D6(18),G6(this)):yEa(this,this.Lx-a)};g.h=BEa.prototype;g.h.Nt=null;g.h.Ke=null;g.h.Oq=!1;g.h.YA=null;g.h.fp=null;g.h.Ku=null;g.h.Ot=null;g.h.ff=null;g.h.Og=-1;g.h.pm=null;g.h.yl=null;g.h.connect=function(a){this.Ot=a;a=L6(this.o,null,this.Ot);D6(3);this.YA=(0,g.I)();var b=this.o.H;null!=b?(this.pm=b[0],(this.yl=b[1])?(this.ff=1,CEa(this)):(this.ff=2,N6(this))):(b6(a,"MODE","init"),this.Ke=new z6(this,void 0,void 0,void 0),this.Ke.Oi=this.Nt,A6(this.Ke,a,!1,null,!0),this.ff=0)};
g.h.WJ=function(a){if(a)this.ff=2,N6(this);else{D6(4);var b=this.o;b.Zf=b.oh.Og;U6(b,9)}a&&this.Hf(2)};
g.h.Us=function(a){return this.o.Us(a)};
g.h.abort=function(){this.Ke&&(this.Ke.cancel(),this.Ke=null);this.Og=-1};
g.h.XA=function(){return!1};
g.h.wE=function(a,b){this.Og=a.qm;if(0==this.ff)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Og;U6(c,2);return}this.pm=c[0];this.yl=c[1]}else c=this.o,c.Zf=this.Og,U6(c,2);else if(2==this.ff)if(this.Oq)D6(7),this.Ku=(0,g.I)();else if("11111"==b){if(D6(6),this.Oq=!0,this.fp=(0,g.I)(),c=this.fp-this.YA,!g.Sd||g.Dc(10)||500>c)this.Og=200,this.Ke.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.fp=this.Ku=(0,g.I)(),this.Oq=!1};
g.h.Aq=function(){this.Og=this.Ke.qm;if(this.Ke.Of)0==this.ff?this.yl?(this.ff=1,CEa(this)):(this.ff=2,N6(this)):2==this.ff&&((!g.Sd||g.Dc(10)?!this.Oq:200>this.Ku-this.fp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.ff?D6(9):2==this.ff&&D6(10);var a=this.o;a.Zf=this.Og;U6(a,2)}};
g.h.Hn=function(){return this.o.Hn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Hf=function(a){this.o.Hf(a)};g.h=O6.prototype;g.h.Ol=null;g.h.pe=null;g.h.Cc=null;g.h.Mt=null;g.h.hp=null;g.h.wz=null;g.h.vp=null;g.h.mn=0;g.h.dR=0;g.h.Hd=null;g.h.uh=null;g.h.Cg=null;g.h.Di=null;g.h.oh=null;g.h.Br=null;g.h.tk=-1;g.h.NB=-1;g.h.Zf=-1;g.h.Oj=0;g.h.Fj=0;g.h.Bi=8;var V6=new g.Xf;g.C(EEa,g.wf);g.C(FEa,g.wf);g.C(GEa,g.wf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Mt=b;this.Ol=c||{};d&&g.u(e)&&(this.Ol.OSID=d,this.Ol.OAID=e);this.F?(I6((0,g.B)(this.Mz,this,a),100),KEa(this)):this.Mz(a)};
g.h.Mz=function(a){this.oh=new BEa(this);this.oh.Nt=null;this.oh.A=this.D;this.oh.connect(a)};
g.h.XA=function(){return 0==this.o};
g.h.CE=function(a){this.uh=null;NEa(this,a)};
g.h.BE=function(){this.Cg=null;this.Cc=new z6(this,this.B,"rpc",this.G);this.Cc.Oi=null;this.Cc.Pt=0;var a=this.wz.clone();g.ln(a,"RID","rpc");g.ln(a,"SID",this.B);g.ln(a,"CI",this.Br?"0":"1");g.ln(a,"AID",this.tk);P6(this,a);if(!g.Sd||g.Dc(10))g.ln(a,"TYPE","xmlhttp"),A6(this.Cc,a,!0,this.vp,!1);else{g.ln(a,"TYPE","html");var b=this.Cc,c=!!this.vp;b.Yj=3;b.Ah=a6(a.clone());xEa(b,c)}};
g.h.wE=function(a,b){if(0!=this.o&&(this.Cc==a||this.pe==a))if(this.Zf=a.qm,this.pe==a&&3==this.o)if(7<this.Bi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Da(c)&&3==c.length)if(0==c[0])a:{if(!this.Cg){if(this.Cc)if(this.Cc.Vk+3E3<this.pe.Vk)R6(this),this.Cc.cancel(),this.Cc=null;else break a;T6(this);D6(19)}}else this.NB=c[1],0<this.NB-this.tk&&37500>c[2]&&this.Br&&0==this.Fj&&!this.Di&&(this.Di=I6((0,g.B)(this.GR,this),6E3));else U6(this,11)}else b!=iGa.b_.o&&U6(this,11);else if(this.Cc==a&&
R6(this),!g.F(b)){c=this.D.parse(b);g.Da(c);for(var d=0;d<c.length;d++){var e=c[d];this.tk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.vp=e[2],e=e[3],null!=e?this.Bi=e:this.Bi=6,this.o=3,this.Hd&&this.Hd.Hz(),this.wz=L6(this,this.Hn()?this.vp:null,this.Mt),OEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Hd&&this.Hd.Gz(e),this.Fj=0)}}};
g.h.GR=function(){null!=this.Di&&(this.Di=null,this.Cc.cancel(),this.Cc=null,T6(this),D6(20))};
g.h.Aq=function(a){if(this.Cc==a){R6(this);this.Cc=null;var b=2}else if(this.pe==a)this.pe=null,b=1;else return;this.Zf=a.qm;if(0!=this.o)if(a.Of)1==b?(b=(0,g.I)()-a.Vk,V6.dispatchEvent(new FEa(V6,a.oj?a.oj.length:0,b,this.Oj)),Q6(this),this.C.length=0):OEa(this);else{var c=a.Bh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.pe||this.uh||1==this.o||2<=this.Oj?d=!1:(this.uh=I6((0,g.B)(this.CE,this,a),PEa(this,this.Oj)),this.Oj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,5);
break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.sK=function(a){if(!g.Va(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.TW=function(a){a?D6(2):(D6(1),QEa(this,8))};
g.h.Us=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Lx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Hd&&this.Hd.isActive(this)};
g.h.Hf=function(a){V6.dispatchEvent(new GEa(V6,a))};
g.h.Hn=function(){return!(!g.Sd||g.Dc(10))};
g.h=REa.prototype;g.h.Hz=function(){};
g.h.Gz=function(){};
g.h.Fz=function(){};
g.h.Hs=function(){};
g.h.FA=function(){return{}};
g.h.isActive=function(){return!0};g.C(W6,g.K);g.h=W6.prototype;g.h.dV=function(){this.Id=Math.min(3E5,2*this.Id);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Id+15E3*Math.random();g.Ku(this.o,a);this.A=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Id=5E3};g.C(X6,REa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Ak=function(a){return this.B.Pi(a)};
g.h.U=function(a,b){return this.B.U.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.uf(this.B),UEa(this),g.uf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Hd=null);d.Hd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.tk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.pc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&LEa(this.o,c)};
g.h.Hz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)LEa(this.o,a[b])}this.U("handlerOpened")};
g.h.Fz=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Hs=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.FA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.pc(a,this.D);return a};
g.h.Gz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),JEa(this.o)):this.U("handlerMessage",new SEa(a[0],a[1]))};
g.h.wX=function(){this.A.isActive();var a=this.o,b=0;a.Cc&&b++;a.pe&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var bFa=(0,g.I)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.C(g7,g.kG);g7.prototype.Fe=function(){return this.o};
g7.prototype.contains=function(a){return!!j6(this.o,a)};
g7.prototype.get=function(a){return a?k6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.C(h7,g.kG);var jGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ha)&&this.QG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ha)||(g.EE(this.Ha),this.Ha=window.NaN)};
g.h.X=function(){this.stop();h7.ga.X.call(this)};
g.h.QG=function(){this.Ha=window.NaN;this.o=g.TE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.yX,this),onError:(0,g.B)(this.xX,this),Nd:(0,g.B)(this.zX,this)})};
g.h.yX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.U("pairingComplete",new e6(c))};
g.h.xX=function(a){this.o=null;a.status&&404==a.status?this.A>=jGa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=jGa[this.A],this.Ha=g.CE((0,g.B)(this.QG,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.zX=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.C(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.HH("yt-remote-lounge-token-expiration")&&fFa(this);g.EE(this.A);this.A=g.CE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);cFa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||fFa(this)};
g.h.remove=function(a,b){var c=i7(this);eFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.xr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.EE(this.A);j7.ga.X.call(this)};
g.h.gL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.fL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.C(m7,g.kG);g.h=m7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.HH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.I)()-144E5<a?0:a)?o7(this):(this.C=(0,g.I)()+3E5,g.GH("yt-remote-fast-check-period",this.C),this.Iw())};
g.h.isEmpty=function(){return g.hc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Rb(this.o,function(b,d){return b&&!!k6(a,d)},this);
n7(this,b)};
g.h.X=function(){g.EE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.X.call(this)};
g.h.Iw=function(){g.EE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=iFa(this);if(g.Vb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.ac(a).join(",")},(0,g.B)(this.MU,this,a),(0,g.B)(this.LU,this))}else n7(this,{}),o7(this)};
g.h.MU=function(a,b){this.A=null;var c=g.ac(iFa(this));if(g.qb(c,g.ac(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.xc("Changing Screen set during request."),this.Iw()};
g.h.LU=function(a){this.xc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.xc=function(a){c7("OnlineScreenService",a)};g.C(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.xr=function(a,b,c,d){this.B.contains(a)?this.B.xr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.Fe=function(a){return a?this.o:g.cb(this.o,(0,g.fe)(this.C,function(a){return!this.contains(a)},this))};
g.h.SG=function(){return(0,g.fe)(this.Fe(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.TG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.uf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.uf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.BX=function(a,b,c,d){g.TE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new e6(d.screen||{});if(!e.name||mFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);mFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Nd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.uf(this.B);g.uf(this.A);p7.ga.X.call(this)};
g.h.tL=function(){nFa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.C(s7,g.kG);g.h=s7.prototype;g.h.Bq=function(a){this.B=a;this.U("sessionScreen",this.B)};
g.h.Je=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.VG=function(){return null};
g.h.Tw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Tw("");s7.ga.X.call(this)};g.C(u7,s7);g.h=u7.prototype;g.h.Sw=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);pFa(this)};
g.h.vk=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Je()},this),(0,g.B)(function(){this.Je(Error("Failed to stop receiver app."))},this)):this.Je(Error("Stopping cast device witout session."))};
g.h.Tw=g.A;g.h.X=function(){this.info("disposeInternal");g.EE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.X.call(this)};
g.h.OV=function(a,b){if(!this.la())if(b){var c=g.Fx(b);if(g.Ga(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":oFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.NA=function(a,b,c,d){lFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.CE((0,g.B)(this.NA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.VG=function(){return this.o};
g.h.CX=function(a){this.la()||a||(t7(this,"Cast session died."),this.Je())};g.C(v7,s7);g.h=v7.prototype;g.h.Sw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.vk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.EE(this.F);this.C?this.C.stop((0,g.B)(this.Je,this,null),(0,g.B)(this.Je,this,"Failed to stop DIAL device.")):this.Je()};
g.h.X=function(){this.o();this.o=g.A;g.EE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.X.call(this)};
g.h.FX=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.A,this.Je())};
g.h.tu=function(a){this.K=i6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,rFa(this));a(b);qFa(this)}else this.G=(0,g.B)(function(){g.EE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,rFa(this));a(b);qFa(this)},this),this.F=g.CE((0,g.B)(function(){this.G()},this),100)};
g.h.EM=function(a,b,c){lFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Bq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.tu(b,c)},this),(0,g.B)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.tu(b,c)},this))};g.C(w7,s7);w7.prototype.stop=function(){this.Je()};
w7.prototype.Sw=g.A;w7.prototype.vk=function(){g.EE(this.o);this.o=window.NaN;var a=k6(this.J.Fe(),this.A.label);a?this.Bq(a):this.Je(Error("No such screen"))};
w7.prototype.X=function(){g.EE(this.o);this.o=window.NaN;w7.ga.X.call(this)};g.C(x7,g.kG);g.h=x7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.yE,this),(0,g.B)(this.vU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.oS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),ZEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.UG,this)),this.B=tFa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.xc("Failed to set initial custom receivers: "+g.Og(a))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.B)(function(a){this.xc("Failed to initialize API: "+g.Og(a));
b(!1)},this))};
g.h.BW=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=k6(this.A.Fe(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=sFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.xc("Failed to set initial custom receivers: "+g.Og(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Tw(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.DW=function(a){this.la()?this.xc("Setting connection data on disposed cast v2"):this.o?this.o.vk(a):this.xc("Setting connection data without a session")};
g.h.EX=function(){this.la()?this.xc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.yE,this),(0,g.B)(this.QU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.UG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.$a(g.y("yt.mdx.remote.debug.handlers_")||[],WEa);g.uf(this.o);x7.ga.X.call(this)};
g.h.xc=function(a){c7("Controller",a)};
g.h.zE=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.rU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.U("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.xc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.xc("Stopping receiver w/o session: "+a.friendlyName)}else this.xc("onReceiverAction_ called without receiver.")};
g.h.oS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.xc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.xc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.xc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.EM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.tu,b))};
g.h.yE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.xc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=k6(this.A.Fe(),c.label);
d&&f6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.uf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.zE,this,this.o)),this.o.vk(null));this.o.Sw(a)}}};
g.h.DX=function(){return this.o?this.o.VG():null};
g.h.QU=function(a){this.la()||(this.xc("Failed to estabilish a session: "+g.Og(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.vU=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.UG=function(){this.la()||(this.B=tFa(this),y7("Updating custom receivers: "+g.Og(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.xc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.DW;x7.prototype.setConnectedScreenStatus=x7.prototype.BW;x7.prototype.stopSession=x7.prototype.EX;x7.prototype.getCastSession=x7.prototype.DX;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.C(T7,g.kG);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.PG=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.tb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Ja(this.PG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.xc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.xc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Ja(this.setVolume,a,b))};
g.h.OF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Og(b.style),g.pc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Ja(this.OF,a,b))};
g.h.Sx=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=U7(this);c.audioTrackId=b.Pb.id;W7(this,c)}else V7(this,g.Ja(this.Sx,a,b))};
g.h.OG=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Ja(this.OG,a,b))};
g.h.NG=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Ja(this.NG,a,b))};
g.h.gA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.gA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.X=function(){GFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.X.call(this)};
g.h.Tx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.ZC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.mU=function(a,b){this.U(a,b)};
g.h.NR=function(a){if(!a)this.qn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.qn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),HFa(this),this.U("remotePlayerChange")};
g.h.MR=function(a){a?(HFa(this),this.U("remotePlayerChange")):this.qn(null)};
g.h.ZR=function(){var a=DFa();a&&S7(this,a)};
g.h.xc=function(a){c7("CP",a)};g.C($7,g.kG);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Og(l));this.o.connect({method:"setPlaylist",
params:g.Og(l)},a,bEa())}else a8("Connecting without params"),this.o.connect({},a,bEa());JFa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.X=function(){c8(this);e8(this);d8(this);g.EE(this.J);this.J=window.NaN;g.EE(this.K);this.K=window.NaN;this.B=null;g.VF(this.V);this.V.length=0;this.o.dispose();$7.ga.X.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.WK=function(){this.F(2)};
g.h.RR=function(){a8("Channel opened");this.O&&(this.O=!1,d8(this),this.M=g.CE((0,g.B)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
fEa(TEa(this.o),this.ba)};
g.h.OR=function(){a8("Channel closed");(0,window.isNaN)(this.D)?p6(!0):p6();this.dispose()};
g.h.PR=function(a){p6();(0,window.isNaN)(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.QR=function(a){a.params?a8("Received: action="+a.action+", params="+g.Og(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Fx(a.params.devices);this.A=(0,g.J)(a,function(a){return new d6(a)});
a=!!g.Qa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
MFa(this,a);break;case "loungeScreenDisconnected":g.ab(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
MFa(this,!1);break;case "remoteConnected":var b=new d6(g.Fx(a.params.device));g.Qa(this.A,function(a){return b?a.id==b.id:!1})||g.Ya(this.A,b);
break;case "remoteDisconnected":b=new d6(g.Fx(a.params.device));g.ab(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":OFa(this,a);break;case "nowPlaying":QFa(this,a);break;case "onStateChange":PFa(this,a);break;case "onAdStateChange":RFa(this,a);break;case "onVolumeChanged":SFa(this,a);break;case "onSubtitlesTrackChanged":NFa(this,a);break;case "nowAutoplaying":TFa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.U("autoplayModeChange",this.C);"DISABLED"==this.C&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":UFa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.lW=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Ak;$7.prototype.ha=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?Y6(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&p6();UEa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.EE(this.J),this.J=g.CE((0,g.B)(this.lW,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.Og(this.qb.o)==g.Og(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.E)(c,function(a){this.U(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Qa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.I)():window.NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.aa=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.aa;$7.prototype.ca=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ca;$7.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Lu(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);LFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.C(g8,g7);g.h=g8.prototype;g.h.Fe=function(a){return this.qd.$_gs(a)};
g.h.contains=function(a){return!!this.qd.$_c(a)};
g.h.get=function(a){return this.qd.$_g(a)};
g.h.start=function(){this.qd.$_st()};
g.h.add=function(a,b,c){this.qd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.qd.$_r(a,b,c)};
g.h.xr=function(a,b,c,d){this.qd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.qd.$_ubk(this.A[a]);this.A.length=0;this.qd=null;g8.ga.X.call(this)};
g.h.AX=function(){this.U("screenChange")};
g.h.IT=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.BX;p7.prototype.$_gsppc=p7.prototype.TG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.xr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.Fe;p7.prototype.$_gos=p7.prototype.SG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Ak;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.K);g.h=y8.prototype;
g.h.X=function(){g.K.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.vE,this);this.o.unsubscribe("remotePlayerChange",this.vn,this);this.o.unsubscribe("remoteQueueChange",this.Cq,this);this.o.unsubscribe("autoplayUpNext",this.RD,this);this.o.unsubscribe("previousNextChange",this.sE,this);this.o.unsubscribe("nowAutoplaying",this.kE,this);this.o.unsubscribe("autoplayDismissed",this.QD,this);this.o=this.D=null};
g.h.TC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.jm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.Sx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.Sx(this.A.getVideoData(1).videoId,c)}};
g.h.LR=function(a){this.L.RK(a)};
g.h.dX=function(a){this.TC("control_subtitles_set_track",g.hc(a)?null:a)};
g.h.bG=function(){var a=this.A.kc("captions","track");g.hc(a)||C8(this,a)};
g.h.fE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.vn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.vn,this)}};
g.h.dT=function(){g.hc(this.G)||fGa(this,this.G);this.H=!1};
g.h.vE=function(a,b){this.F.stop();2==b&&this.ZF()};
g.h.vn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.playerState){case 1081:case 1:A8(this,new g.bQ(8));this.YF();break;case 1085:case 3:A8(this,new g.bQ(9));break;case 1083:case 0:A8(this,new g.bQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.bQ(4));break;case 2:A8(this,new g.bQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.bQ(64));break;case -1E3:A8(this,new g.bQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,fGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.zG()}else eGa(this)};
g.h.sE=function(){this.A.U("mdxpreviousnextchange")};
g.h.Cq=function(){B8(this)||eGa(this)};
g.h.VJ=function(){this.o.gA()};
g.h.RD=function(a){a&&(a=g.TE("/watch_queue_ajax",{method:"GET",jd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.oV,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.oV=function(a,b){var c=new g.qP(g.Z(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.kE=function(a){(0,window.isNaN)(a)||this.A.U("mdxnowautoplaying",a)};
g.h.QD=function(){this.A.U("mdxautoplaycanceled")};
g.h.MP=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.PG(a)};
g.h.zG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.V);a.muted?this.A.mute():this.A.qg();this.A.setVolume(a.volume);this.V=this.B.R(this.A,"onVolumeChange",this.fE)}};
g.h.YF=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.bQ(8));z8(this,P7(a));this.C.start()}};
g.h.ZF=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){hGa(this,a.state)};g.r(F8,g.UY);F8.prototype.L=function(){var a=this.B.kc("remote","receivers");a&&1<a.length&&!this.B.kc("remote","quickCast")?(this.J=g.sb(a,this.F,this),g.VY(this,(0,g.J)(a,this.F)),a=this.B.kc("remote","currentReceiver"),this.Gf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.Ff=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
F8.prototype.Ld=function(a){g.UY.prototype.Ld.call(this,a);this.B.ed("remote","currentReceiver",this.J[a]);this.D.Rb()};g.r(G8,g.UU);g.h=G8.prototype;g.h.create=function(){ZFa(g.tN(g.Z(this.player)));this.D.push(g.xG("yt-remote-before-disconnect",this.HR,this));this.D.push(g.xG("yt-remote-connection-change",this.wU,this));this.D.push(g.xG("yt-remote-receiver-availability-change",this.tE,this));this.D.push(g.xG("yt-remote-auto-connect",this.uU,this));this.D.push(g.xG("yt-remote-receiver-resumed",this.tU,this));this.tE()};
g.h.load=function(){this.player.jv();g.UU.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=dGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&(this.J=a||0,this.player.U("progresssync",a,void 0));gGa(this,this.F,this.F);g.n0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.B=this.A;g.vf(this.C,this.o);this.o=this.C=null;g.UU.prototype.unload.call(this);g.n0(this.player.app,5)};
g.h.X=function(){g.yG(this.D);g.UU.prototype.X.call(this)};
g.h.cn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.TC.apply(this.C,[a].concat(g.ea(c)))};
g.h.MK=function(){return this.loaded?this.C.suggestion:null};
g.h.eg=function(){return this.o?U7(this.o).eg:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.xP=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Z(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Pc():!a.isAdPlaying()&&this.player.Pc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+N7(a):a.C}};
g.h.yP=function(){this.o&&this.o.NG()};
g.h.zP=function(){this.o&&this.o.OG()};
g.h.HR=function(a){1==a&&(this.K=this.o?U7(this.o):null)};
g.h.wU=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.uf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.zC(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.tE=function(){this.H=[this.A].concat(aGa());var a=s8()||this.A;H8(this,a);this.player.za("onMdxReceiversChange")};
g.h.uU=function(){var a=s8();H8(this,a)};
g.h.tU=function(){this.B=s8()};
g.h.Mc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&J7(),!0):!1}};
g.h.AP=function(){Y7(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.yc=function(){return!1};g.SX.remote=G8;})(_yt_player);
